export enum SeaceDataTypes {
  //SEACE
  SIN_GESTION = 100,
  //LEADS
  EN_GESTION = 101,
  SIN_DATOS_DE_CONTACTO = 102,
  NO_UBICADO = 103,
  NO_INTERESADO = 104,
  TIENE_BROKER = 105,
  NO_REQUIERE_FIANZA = 106,
  TRABAJA_CON_EL_BANCO = 107,
  NO_CALIFICA = 108,
  OTROS = 109,
  REPETIR_LLAMADA = 111,
  //CLIENTES
  CLIENTE_POTENCIAL = 110,
  INTERESADO = 112,
  RECEPCION_DE_DOCUMENTOS = 114,
  ARMADO_DE_PROPUESTA = 115,
  ENVIO_A_OPERACION = 116,
  //OPERACIONES
  RECIBIDO_EN_OPERACION = 117,
  VERIFICACION_FINANCIERA_Y_DOCUMENTOS = 118,
  INGRESAR_LA_OPERACION = 119,
  RECONSIDERACION = 120,
  ENVIAR_TERMINOS_Y_CONDICIONES = 121,
  REDACCION_DE_DOCUMENTACION_LEGAL = 122,
  FIANZAS_LISTAS_PARA_EMITIRLAS = 123,

  SOLICITUD_DE_ATENCION = 130,
  SOLICITUD_DE_EMISION = 131,
  EMITIDO = 132,
  PAGADO = 133,
  EN_COTIZACION = 136,
  PENDIENTE_DE_PAGO = 137,

  // RECIBIDO_EN_SEGUROS=130,
  // EN_PROCESO = 131,
  // ATENDIDO = 132,
  // SOLICITUD_DE_EMISION = 133,
  // EMITIDO = 134,
  // CLIENTE_PAGADO = 135,

  ENTREGADO_AL_CLIENTE = 200,
  ARCHIVADO = 225,

  // Fideicomisos prospectos
  EN_NEGOCIACION = 150,
  ACEPTADO = 151,
  DESESTIMADO = 152,
  CLIENTE_FIDEICOMISO = 159,

  //Renovaciones
  NOTIFICAR_AL_CLIENTE = 260,
  REVISION_DE_DOCUMENTOS = 261,
  ENVIO_DE_CORREO_A_LA_ASEGURADORA = 262,
  CONFIRMACIÓN_DE_RENOVACIÓN_Y_EMISION_DE_LA_FACTURA = 263,
  RECOJO_DE_LA_FIANZA_Y_ENTREGA_DE_RENOVACION = 264,
  FIANZA_RENOVADA = 265,

  //LIBERACIONES
  DEVOLUCION_DE_FIANZA_E_INGRESO_DE_SOLICITUD = 270,
  VALIDACION_DE_DOCUMENTOS_Y_AVANCE_DE_OBRA = 271,
  SEGUIMIENTO = 272,
  APROBACION = 273,
  DEUDAS_PENDIENTES = 274,
  AREA_DE_TESORERIA = 275,
  FIANZA_LIBERADA = 276,
  NO_RENOVAR = 277,

  // COBRANZAS
  NOTIFICAR_DEUDA = 280,
  RESPUESTA_DEL_CLIENTE_Y_ANOTOCION_DE_COMPROMISO = 281,
  SUBIR_DOCUMENTOS = 282,
  ANULADO = 290,
}

export const data = {
  start_date: '2025-12-01',
  end_date: '2025-12-31',
  comercials: [
    {
      name: 'Juan Perez', //NOMBRE DEL COMERCIAL
      worker_id: '1e027181-e19c-4275-9057-939ef025a688', //ID DEL COMERCIAL
      total_leads: [
        {
          product: 'Carta Fianza', //TIPO DE PRODUCTO
          quantity: 50, //CANTIDAD DE LEADS TOTALES
        },
      ],
      assigned_leads: 25, //CANTIDAD DE LEADS ASIGNADOSNUEVO ESTADO 101
      contacted_leads: 20, //CANTIDAD DE LEADS CONTACTADOS CON ESTADO DIFERENTE A 101
      repet_calls: 5, //CANTIDAD DE LEADS PARA REPETIR LLAMADA ESTADO 111
      deals_closed: 5, //CANTIDAD DE DEALS PARA HACER SEGUIMIENTO ESTADO DE 112 AL 116
      leads_closed: 10, //CANTIDAD DE LEADS CERRADOS ESTADO 200 PRODUCTO VENDIDO
      conversion_rate: 20, //TASA DE CONVERSION EN PORCENTAJE
      //TIEMPO DE RESPUESTA PROMEDIO EN DIAS Y HORAS(desde que se asigna el lead hasta que se contacta)
      average_response_time_hours: 48,
    },
  ],
  ranking_global: [
    {
      name: 'Juan Perez', //NOMBRE DEL COMERCIAL
      total_product: {
        product: 'Carta Fianza', //TIPO DE PRODUCTO
        quantity: 50, //CANTIDAD DE LEADS TOTALES(esto es li mismo de deals del estado 112 al 116)
      },
      worker_id: '1e027181-e19c-4275-9057-939ef025a688', //ID DEL COMERCIAL
    },
  ],
};
